model_list:
  - model_name: gemini-2.5-pro

    litellm_params:

      model: gemini/gemini-2.5-pro

      api_key: AIzaSyCh29oyi05LkzsOzEM_9CtsAaOejae3Ous
  - model_name: gemini-2.5-pro

    litellm_params:

      model: gemini/gemini-2.5-pro

      api_key: AIzaSyB0wthDAV3iwfedSIJrTfaTVKpLBDGdnM

  - model_name: gemini-2.5-pro

    litellm_params:

      model: gemini/gemini-2.5-pro

      api_key: AIzaSyC_0DQnjoqwdbb7nbPSzREIUGRPTgx5HTc

litellm_settings:

  set_verbose: false

  port: 4000

  host: 0.0.0.0



general_settings:

  master_key: mT6K=ebXTwk2{z^S2



router_settings:

  routing_strategy: simple-shuffle
